import home1 from "../img/house-1.jpeg";
import home2 from "../img/house-2.jpeg";
import home3 from "../img/house-3.jpeg";
import home4 from "../img/house-4.jpeg";
import home5 from "../img/house-5.jpeg";
import home6 from "../img/house-6.jpeg";

export const HOME_DATA = [
  {
    id: 1,
    name: "Beautifull Family House",
    location: "宮城県栗原市若柳字川北新町",
    rooms: "4LDK",
    area: "325 m",
    price: "1.200.000",
    img: home1,
  },
  {
    id: 2,
    name: "Modern Glass Villa",
    location: "宮城県栗原市若柳字川南堤通",
    rooms: "5K",
    area: "450 m",
    price: "2.700.000",
    img: home2,
  },
  {
    id: 3,
    name: "Cozy Country House",
    location: "宮城県栗原市若柳武鎗字町舘",
    rooms: "3LDK",
    area: "250 m",
    price: "900.000",
    img: home3,
  },
  {
    id: 4,
    name: "Large Rustical Villa",
    location: "宮城県栗原市築館字下待井59-130",
    rooms: "5DK",
    area: "480 m",
    price: "1.900.000",
    img: home4,
  },
  {
    id: 5,
    name: "Majestic Palace House",
    location: "宮城県栗原市若柳武鎗字町舘",
    rooms: "6LDK",
    area: "430 m",
    price: "9.200.000",
    img: home5,
  },
  {
    id: 6,
    name: "Modern Family Apartment",
    location: "宮城県栗原市若柳武鎗字町舘",
    rooms: "3K",
    area: "180 m",
    price: "700.000",
    img: home6,
  },
  {
    id: 7,
    name: "Beautifull Family House",
    location: "宮城県栗原市若柳字川北新町",
    rooms: "4LDK",
    area: "325 m",
    price: "1.200.000",
    img: home1,
  },
  {
    id: 8,
    name: "Modern Glass Villa",
    location: "宮城県栗原市築館字下待井59-130",
    rooms: "4DK",
    area: "450 m",
    price: "2.700.000",
    img: home2,
  },
  {
    id: 9,
    name: "Cozy Country House",
    location: "宮城県栗原市若柳武鎗字町舘",
    rooms: "3K",
    area: "250 m",
    price: "900.000",
    img: home3,
  },
  {
    id: 10,
    name: "Large Rustical Villa",
    location: "宮城県栗原市若柳武鎗字町舘",
    rooms: "6LDK",
    area: "480 m",
    price: "1.900.000",
    img: home4,
  },
  {
    id: 11,
    name: "Majestic Palace House",
    location: "宮城県栗原市若柳武鎗字町舘",
    rooms: "6LDK",
    area: "430 m",
    price: "9.200.000",
    img: home5,
  },
  {
    id: 12,
    name: "Modern Family Apartment",
    location: "宮城県栗原市若柳武鎗字町舘",
    rooms: "3DK",
    area: "180 m",
    price: "700.000",
    img: home6,
  },
];
